sudo: required
services:
    - docker

beofre-install:
    - docker build -t psuedoname/docker-react -f Dockerfile.dev .
    
script:
    - docker run psuedoname/docker-react npm run test -- --coverage
    
deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    name: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-south-1-612625938287"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRET_KEY"
        